### ISSUE TITLE
Incompatible with homey pro?

### ISSUE THREAD

**Issue by rogerwesterbo** [maxxie01/Renkforce#1]
Hi, I'm getting error message about renkforce app is incompatible with homey pro...

**Comment by maxxie01** [comment]
That is because I do't rebuild the app for Homey 2.0, the new version. I will do that in the near future but on this moment I don't have the time for it. Sorry.

**Comment by peteresser** [comment]
@maxxie01 I think you made this compatible recently, but I’m unable to install the app. Also a Homey Pro user. Are you aware of this? Perhaps I can help to solve this?

**Comment by HakkaMc** [comment]
I don't have Pro version but can't install it too. And also can't install it manually by command line "homey app install". I think Max has to update the project to Homey 2.0 (as he said).

@maxxie01 Please do it as soon as possible. If you do it within a month and it will work with my Conrad plugs I will send you 20 euros. I'am brand new in Homey system so it's not possible for me to do a fork of your project and correct it for using on Homey 2.0.

**Comment by maxxie01** [comment]
I need time, not money. But relax I am busy with the conversion to 2.0.

**Comment by maxxie01** [comment]
Conversion is done. Now I am testing the app and need to push to the app store.

**Comment by maxxie01** [comment]
@rogerwesterbo @peteresser @HakkaMc 

You can use the URL https://homey.app/a/nl.maxxie.renkforce/test/ to test the new app. The app is now in the certification state by Athom.

Max

**Comment by HakkaMc** [comment]
I have found out that my Conrad sockets are probably something different to Renkforce. But nevermind. I have downloaded sourcecode from github and changed signal settings (sof, eof, words) and binary frame structure and voila, it's working! Thank you Max, you helped me a lot!

Häkka

**Comment by maxxie01** [comment]
Oke. the new version is now available in the Homey app store.
